name: black
on: pull_request
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          python-version: 3.11
      - run: |
          black --check --verbose .
          black --check --verbose ./dir1
          black --check --verbose ./dir2
